un-ts/eslint-plugin-import-x

README.md
package.json

Clarify _why_ this package is a good drop-in substitute to `eslint-plugin-import`

Add purpose to intro in README.md

---

README.md

The repo link got redirected, and it took me a while to understand what was happening. I think it would be better to link to the context for existing `eslint-plugin-i` so that it can be understood easily and migrate.
I don't know what's the best place to put that link - feel free to move it to wherever makes more sense.

docs: add link to package rename

---

README.md

Update README to correctly configure import-x instead of import

---

.changeset/hot-sheep-visit.md
package.json

tslib is required as a runtime dependency but not installed in this project.
Fixes #73.

fix: cannot find module 'tslib'

---

.changeset/fifty-ladybugs-occur.md
src/utils/parse.ts

`typescript-eslint` v8 beta has made `projectService` stable (`EXPERIMENTAL_useProjectService` is now just `projectService`) thus previous `delete parserOptions.EXPERIMENTAL_useProjectService` no longer works on typescript-eslint v8.
The PR adds `delete parserOptions.useProjectService`. When `typescript-eslint` v8 becomes stable, we might want to adapt https://github.com/typescript-eslint/typescript-eslint/pull/9233 (https://github.com/typescript-eslint/typescript-eslint/issues/8428)

fix: enable isolate mode w/ typescript-eslint v8

---

.changeset/short-bees-sell.md
package.json
src/types.ts
src/utils/export-map.ts

Currently the plugin loses `languageOptions` when creating a child context (when using a flat config). This causes errors when plugin tries to use the default parser, i.e. `languageOptions.parser`
I've also created [a reproduction](https://github.com/kosmotema/epix-parser) for this bug

fix: add languageOptions to ChildContext

---

package.json
src/utils/export-map.ts
yarn.lock

Continues from #85.
Unlike `dequal`, `stable-hash` uses shallow comparison and referential equality only (so mutable Object, Set, and Map won't have the same hash after mutation). And `stable-hash` outputs meaningful hash instead of version.
cc @kosmotema

refactor: replace `dequal` w/ `stable-hash`

---

.changeset/bright-taxis-smell.md
src/rules/no-extraneous-dependencies.ts
test/rules/no-extraneous-dependencies.spec.ts

Backport https://github.com/import-js/eslint-plugin-import/pull/3012

fix: allow incorrect file path in extraneous deps check

---

.changeset/grumpy-games-shake.md
.changeset/sixty-avocados-stare.md
README.md
docs/rules/dynamic-import-chunkname.md
src/rules/dynamic-import-chunkname.ts
test/rules/dynamic-import-chunkname.spec.ts

Backport https://github.com/import-js/eslint-plugin-import/pull/3004

feat: disallow import chunkname w/ webpack eager mode

---

.changeset/fifty-toes-report.md
src/rules/no-duplicates.ts
src/utils/lazy-value.ts

perf(#103): make `no-duplicates` way faster

---

.changeset/shiny-birds-design.md
package.json

Fixes #76 and #88
cc @tetarchus

chore: an attempt to bump `eslint-plugin-import-x` into 3.x

---

.changeset/heavy-kangaroos-relax.md
.changeset/wicked-mangos-suffer.md
src/rules/no-cycle.ts
src/utils/export-map.ts
src/utils/ignore.ts
src/utils/import-type.ts
src/utils/lazy-value.ts
src/utils/module-cache.ts
src/utils/resolve.ts

perf: make `ExportMap` util and `no-cycle` rule faster

---

.changeset/hot-fireants-provide.md
docs/rules/no-unused-modules.md
src/rules/no-unused-modules.ts
test/rules/no-unused-modules.spec.ts

Direct port of https://github.com/import-js/eslint-plugin-import/pull/3011.
Fixes: https://github.com/un-ts/eslint-plugin-import-x/issues/86.

feat: Add `ignoreUnusedTypeExports` option to `no-unused-modules`

---

yarn.lock

Tried this while looking into the flow issues, figured I'd give you the option to include it. Feel free to close, it's only for slimming up local dev a tad.
Uses [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) since Yarn 1 didn't include this functionality.

npx yarn-deduplicate to coalesce babel deps

---

package.json
src/utils/parse.ts
yarn.lock

Use `withoutProjectParserOptions` from `@typescript-eslint/typescript-estree`.
Follows #93. See also https://github.com/typescript-eslint/typescript-eslint/pull/9233, https://github.com/typescript-eslint/typescript-eslint/issues/8428

refactor: isolate parsing w/ typescript-eslint v8

---

.changeset/great-dodos-dream.md
package.json
src/config/flat/electron.ts
src/config/flat/errors.ts
src/config/flat/react-native.ts
src/config/flat/react.ts
src/config/flat/recommended.ts
src/config/flat/stage-0.ts
src/config/flat/typescript.ts
src/config/flat/warnings.ts
src/index.ts
src/types.ts
src/utils/ignore.ts

This change adds support for ESLint's new Flat config system.  It maintains backwards compatibility with eslintrc style configs as well.
To achieve this, we're now dynamically creating flat configs on a new `flatConfigs` export.  I was a bit on the fence about using this convention, or the other convention that's become prevalent in the community: adding the flat configs directly to the `configs` object, but with a 'flat/' prefix.  I like this better, since it's slightly more ergonomic when using it in practice.  e.g. `...importX.flatConfigs.recommended` vs `...importX.configs['flat/recommended']`, but i'm open to changing that.
Example Usage
```js
import importPlugin from 'eslint-plugin-import';
import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
export default …
```

feat: add flat config support

---

README.md

Greetings,
I noticed the README is currently missing reference to the flat config which has been supported on new version [4.1.0](https://github.com/un-ts/eslint-plugin-import-x/releases/tag/v4.1.0).
I added two new sections under "Installation" section:
- "Configuration (legacy: `.eslintrc*`)" contains the previous content of "Installation that was after installlation command
- "Configuration (new: `eslint.config.js`)" contains two simple examples (js and ts). 
They are both wrapped in a `<details />` tag to avoid they take too much space.
On the bottom of the section I added a link to reference the folder where all flat configs are present
---
I also added a few alert on the already present information to make them more visible ([Github markdown …

docs: add flat config configuration

---

README.md
src/config/flat/typescript.ts
src/config/typescript.ts

Followup of https://github.com/un-ts/eslint-plugin-import-x/pull/135#issuecomment-2322818957

feat: replace node with ts resolver in `typescript` configs

---

.github/workflows/ci.yml

I made a small improvement to the `ci` workflow.
Using `matrix.include` feature I integrate the configuration matrix with two values:
It controls the execution of `Lint` step. The behaviour should remain the same.
Instead of running coverage on each matrix combination I have limited it only to the node 20 combination.
---
> [!NOTE]
> The main advantage is that  the control value of steps execution is located near the matrix values,
> so they can be updated more easily.
> [!TIP]
> More information about this feature can be found on [GitHub Actions documentation reference](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#expanding-or-adding-matrix-configurations).

ci: use `matrix.include` to set data for optional steps

---

.changeset/light-apples-rhyme.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.ts
test/rules/no-extraneous-dependencies.spec.ts

Closes #141.
This PR also includes some typo fixes in "no-extraneous-dependencies.md".
Also note that I had some difficulties in setting up this repo. After a clone, I typed "yarn" to install the project dependencies. Then, "npm run build" succeeded, but "npm run test" and "npm run lint" both failed from a completely fresh repo. Is that expected?

feat: whitelist option for no-extraneous-dependencies

---

.changeset/twenty-jars-fix.md
package.json
src/rules/no-rename-default.ts
src/utils/parse.ts
yarn.lock

Fixes https://github.com/nuxt/eslint/issues/494
cc @antfu @Revadike

fix: avoid side effects from `@typescript-eslint/typescript-estree`

---

.changeset/flat-doors-chew.md
src/rules/no-unused-modules.ts

Fix initialization of option `src` to again default to `process.cwd()` per [the documentation](https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-unused-modules.md#options).
de896f46b1e3d3bcc51015d2e0269e6ae80dc87d (released in v0.3.1) added an incorrect [default parameter value of `[]` for `src`](https://github.com/un-ts/eslint-plugin-import-x/blob/master/src/rules/no-unused-modules.ts#L309). This introduced a regression that breaks discovery of source files unless option `src` is explicitly set by the consumer, resulting in false positives for `unusedExports`.

fix(`no-unused-modules`): default `src` to `process.cwd()` again

---

.changeset/mighty-ladybugs-agree.md
src/rules/no-duplicates.ts
test/rules/no-duplicates.spec.ts

I ran into this issue in one of my repositories with Koa:
```typescript
import { type Middleware } from 'koa';
import type Koa from 'koa';
```
The rule was rewriting it to invalid syntax:
```typescript
import Koa, type { Middleware } from 'koa';
```
One approach could be just to allow it to:
```typescript
import Koa, { type Middleware } from 'koa';
```
However, I don't think this plugin should be changing type imports into value imports in this scenario.
Therefore, after this change, it leaves the imports alone. I hope this should be not too controversial given it was previously producing invalid syntax. 
I am of course not an expert in this code :) but the change seems suspiciously simple. Are there any additional test cases I can add to help verify this?

Fix incorrect no-duplicates prefer-inline default type import handling

---

.changeset/tidy-crews-sit.md
docs/rules/extensions.md
src/rules/extensions.ts
test/rules/extensions.spec.ts

upstream has implemented this in https://github.com/import-js/eslint-plugin-import/commit/d225176343d491db07a1c9e6e521ea90f169c928
basically ported the feature and test cases from there
idk how to add this to changelog, would be nice if someone did that for me :>

`extensions`: added `checkTypeImports` option

---

.changeset/polite-snakes-buy.md
src/rules/extensions.ts

Refine `extensions` rule  `Options`:
- since the function used by the rule to get file extension is called is called `getModifier` I renamed all relevant information using `modifier` name.
- Refined `Options` with more explicit array types
- Changed `buildProperties` checks to avoid type checking errors

fix(extensions): correct `Options` type

---

.changeset/witty-apples-chew.md
src/rules/no-extraneous-dependencies.ts

`no-extraneous-dependencies` rule `Options` type contains incorrect definition for the following properties:
- `devDependencies`
- `optionalDependencies`
- `peerDependencies`
- `bundledDependencies`
They should be `boolean | string[]` as stated in the rule schema below:
https://github.com/un-ts/eslint-plugin-import-x/blob/3a4517031a15303733589c8441d00233fd568abc/src/rules/no-extraneous-dependencies.ts#L372-L375

fix(no-extraneous-dependencies): correct some `Options` type properties

---

test/rules/no-useless-path-segments.spec.ts
test/rules/no-webpack-loader-syntax.spec.ts
test/utils.ts

During #174 and #175 I noticed that in test files rule `options` types are not inferred inside `test` functions.
To avoid this problem I added `createRuleTestCaseFunction` that returns a function that can be used to generate both valid and invalid cases.
This function accept only 1 type parameter which is used to infer rule `Options` and `MessageIds` which are not exported from the rule source file.
The immediate advantage is that now types are properly inferred from the rule declaration and a type error is reported if the rule `Options` type doesn't match them:
<details>
<summary>Intellisense on rule options screenshot</summary>
</details>
---
Additionally also rule `MessageIds` type can be inferred and provided as autocomplete suggestions:
<details>
<summary>Intellisense on rule message …

test: create utility function to infer rule types

---

src/rules/extensions.ts
test/rules/extensions.spec.ts

Follow up of #176.
`extensions` rule right now has two messages:
https://github.com/un-ts/eslint-plugin-import-x/blob/75c4e365d89ec51abc7de772d245eccd779cc9fb/src/rules/extensions.ts#L169-L173
`missing` message is populate here:
https://github.com/un-ts/eslint-plugin-import-x/blob/75c4e365d89ec51abc7de772d245eccd779cc9fb/src/rules/extensions.ts#L262-L266
However testing this message with `extension`data property set like `extension: '"js" '`:
```ts
test({
code: '...'
errors: [
{ messageId: 'missing', data: { extension: '"js" ', importPath: './foo'  } }
]
})
```
Seems a bit awkward IMHO.
----
To simplify `extension` data property I added a separate message `missingKnown`.
I also refined Options type.

test(extensions): migrate to `createRuleTestCaseFunction`

---

.changeset/orange-nails-attack.md
src/index.ts
src/types.ts
src/utils/legacy-resolver-settings.ts
src/utils/resolve.ts
test/fixtures/foo-bar-resolver-v3.js
test/utils/resolve.spec.ts

The PR implements the new resolver design I proposed in https://github.com/un-ts/eslint-plugin-import-x/issues/40#issuecomment-2381444266
----
Like the ESLint flat config allows you to use any js objects (e.g. import and require) as ESLint plugins, the new `eslint-plugin-import-x` resolver settings allow you to use js objects as custom resolvers through the new setting `import-x/resolver-next`:
```js
// eslint.config.js
import { createTsResolver } from '#custom-resolver';
const { createOxcResolver } = require('path/to/a/custom/resolver');
const nodeResolverObject = {
interfaceVersion: 3,
name: 'my-custom-eslint-import-resolver',
resolve(modPath, sourcePath) {
};
};
module.exports = {
settings: {
// multiple resolvers
'import-x/resolver-next': [
nodeResolverObject, …
```

feat: implement custom resolver interface v3

---

.changeset/tasty-llamas-deny.md
src/rules/no-duplicates.ts
test/rules/no-duplicates.spec.ts

There was a bug when merging a type-import with a value-import, when the type import uses `import-as` syntax.
This handles the `import-as` case.

fix(`no-duplicates`): merge type import `as` with value import

---

.changeset/tame-melons-notice.md
src/rules/no-duplicates.ts
test/rules/no-duplicates.spec.ts

When merging imports, the `type` prefix would get inserted on a different line.
This changes the auto-fix so it inserts new type imports after the last token inside the import bracket, as opposed to before the closing bracket token.

 fix(no-duplicates): type prefix without new line

---

.changeset/witty-garlics-destroy.md
package.json
src/index.ts
src/node-resolver.ts
test/node-resolver.spec.ts
yarn.lock

The PR implements a default resolver that supports `exports` from `package.json`.
More details can be found at #208.
Fixes #208.

feat: implement a resolver that supports `exports`

---

.changeset/kind-swans-invent.md
package.json
src/index.ts
src/node-resolver.ts
test/node-resolver.spec.ts

#209 added `enhanced-resolve` to devDependencies, instead of dependencies, causing this plugin to fail for anyone using yarn PnP.

Move enhanced resolve to prod deps

---

docs/rules/consistent-type-specifier-style.md
src/rules/consistent-type-specifier-style.ts

The default value in the docs are incorrect.
In the code, the default is `prefer-top-level`:
https://github.com/un-ts/eslint-plugin-import-x/blob/v4.6.1/src/rules/consistent-type-specifier-style.ts#L120

docs(consistent-type-specifier-style): correct default option

---

docs/rules/no-deprecated.md

Add note about using with TypeScript

---

src/index.ts

I am working on the eslint config inspector for my big flat config and I saw many anonymous configs where one of them is related to `import` so I added names in the flat configs

Added name in flat config for eslint config inspector

---

.changeset/silver-wombats-sit.md
.prettierignore
.prettierrc.mjs
package.json
src/node-resolver.ts

`default` should be last matched, `module` should be in `mainFields`.
Reference https://github.com/isaacs/resolve-import/blob/main/src/resolve-conditional-value.ts

fix: change default `conditions` and `mainFields`

---

.changeset/ninety-coins-wave.md
package.json
src/global.d.ts
src/node-resolver.ts
yarn.lock

close https://github.com/un-ts/eslint-plugin-import-x/issues/242#issuecomment-2726997425

fix: align `pnpapi` resolved path with `enhanced-resolve`

---

README.md

Motivation: https://github.com/un-ts/eslint-plugin-import-x/issues/92#issuecomment-2750642552
Document the `bun` boolean option from [`eslint-import-resolver-typescript@4.2.0`](https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v4.2.0), to allow resolving Bun modules like `bun:test`
Also, fix the ESM import to use the `import * as` syntax for `eslint-import-resolver-typescript`
See also original issue:
- https://github.com/un-ts/eslint-plugin-import-x/issues/92
cc @SukkaW @JounQin

Document eslint-import-resolver-typescript `bun` option, fix ESM import
